import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@radix-ui/themes/styles.css';
import TopHeader from '@/components/Header/TopHeader';
import BottomHeader from '@/components/Header/BottomHeader';
import Footer from '@/components/Footer/Footer';
import { Theme } from '@radix-ui/themes';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Properties for sale in Malaga',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme>
          <TopHeader />
          <BottomHeader />
          {children}
          <Footer />
        </Theme>
      </body>
    </html>
  )
}
